export const ADD_POSTS = "POSTS/ADD_POSTS";
export const REQUEST_POSTS = "POSTS/REQUEST_POSTS";
export const REQUEST_SINGLE_POST = "POSTS/REQUEST_POST";
export const ADD_SINGLE_POST = "POSTS/ADD_SINGLE_POST";
export const REMOVE_SINGLE_POST = "POSTS/REMOVE_SINGLE_POST";